slam_node:
  ros__parameters:
    onnx_model : /home/hesam/Desktop/depth_node/model/metric3d/model.onnx
    image_width: 960
    image_height: 512
    image_topic : "/kitti/camera_color_left/image_raw"
    model : metric3d
    params_folder_path : "/home/hesam/Desktop/Repos/Kimera-VIO/params"
    
utils_node :
  ros__parameters:
    dataset : KITTI 

optimizer_node:
  ros__parameters:
    acc_std: 0.4
    gyro_std: 0.2
    integration_std: 0.1
    optimization_interval_ms : 100
    imu_topic : "/kitti/oxts/imu"