slam_node:
  ros__parameters:
    onnx_model : /home/hesam/Desktop/active/depth_node/model/unidepth/unidepthv2_vits14._big.onnx
    image_width: 1204
    image_height: 350
    image_topic : "/kitti/camera_color_left/image_raw"
    model : unidepth
    
utils_node :
  ros__parameters:
    dataset : metric3d 

optimizer_node:
  ros__parameters:
    acc_std: 0.4
    gyro_std: 0.2
    integration_std: 0.1
    optimization_interval_ms : 100
    imu_topic : "/kitti/oxts/imu"