slam_node:
  ros__parameters:
    onnx_model : /home/hesam/Desktop/playground/depth_node/model/unidepth/unidepthv2_vits14_simp.onnx
    image_width: 644
    image_height: 364
    image_topic : "/kitti/camera_color_left/image_raw"
    model : unidepth
    
utils_node :
  ros__parameters:
    dataset : KITTI 