slam_node:
  ros__parameters:
    onnx_model : /home/hesam/Desktop/playground/depth_node/model/unidepthv2_vits14_camera.onnx
    image_width: 644
    image_height: 364
    image_topic : "/camera2/left/image_raw"

utils :
  ros__parameters:
    dataset : KITTI 